# This YAML file demonstrates building a gradle console app and deploying it to your
# Timberlea account via secure copy.

# NOTE: It does not upload your test results to GitLab, you will need
# to figure that out still.

# NOTE: You will need to adjust the following variable to the build output of your app
#       right now it's configured to deploy an Android APK file from another class I taught.
# variables:
#   EXECUTABLE_TO_DEPLOY: "app/build/outputs/apk/debug/app-debug.apk"
#   DESTINATION_FILE: "App-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.apk"

stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd backend
    - echo "Building backend"
    - mvn clean install
  artifacts:
    paths:
    - backend/target/site/*
  tags:
    - dalfcs_docker_autoscale
  only:
    - Develop

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - echo "Building frontend"
    - npm install
    - npm install -g @vue/cli-service
    - npm install @vue/cli-plugin-babel
    - npm run build
  artifacts:
    paths:
    - frontend/target/site/*
  tags:
    - dalfcs_docker_autoscale
  only:
    - Develop
    

test-backend:
  stage: test
  image: maven:latest
  script:
    - cd backend
    - echo "Testing backend"
    - mvn clean test
  artifacts:
    paths:
    - backend/target/site/*
  tags:
    - dalfcs_docker_autoscale
  only:
    - Develop  

deploy-backend:
  stage: deploy
  artifacts:
    paths:
    - backend/target/site/*
  script:
    - echo "Deploying Success"
    - apt update
    - apt install curl
    - curl -s https://api.render.com/deploy/srv-ci6gjtdiuieb62u17e5g?key=-fU8hgE5Ymw
  tags:
    - dalfcs_docker_autoscale
  only:
    - Release