# This YAML file demonstrates building a gradle console app and deploying it to your
# Timberlea account via secure copy.

# NOTE: It does not upload your test results to GitLab, you will need
# to figure that out still.

# NOTE: You will need to adjust the following variable to the build output of your app
#       right now it's configured to deploy an Android APK file from another class I taught.
# variables:
#   EXECUTABLE_TO_DEPLOY: "app/build/outputs/apk/debug/app-debug.apk"
#   DESTINATION_FILE: "App-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.apk"

stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd backend
    - echo "Building backend"
    - mvn clean install
  artifacts:
    paths:
    - backend/target/*.jar
  tags:
    - dalfcs_docker_autoscale


build-frontend:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - echo "Building frontend"
    - npm install
    - npm install -g @vue/cli-service
    - npm install @vue/cli-plugin-babel
    - npm run build
  tags:
    - dalfcs_docker_autoscale

test-backend:
  stage: test
  image: maven:latest
  script:
    - cd backend
    - echo "Testing backend"
    - mvn clean test
  tags:
    - dalfcs_docker_autoscale

push_jar_to_github:
  stage: deploy
  script:
    - echo "Pushing .jar file to GitHub"
    - git config --global user.email "dev2104patel@gmail.com"
    - git config --global user.name "dev-patel2104"
    - git clone https://github.com/dev-patel2104/ASDC_Project.git
    - cp target/VendorValley-0.0.1-SNAPSHOT.jar ASDC_Project/backend/
    - cd ASDC_Project/backend/
    - git checkout -b Release
    - git add VendorValley-0.0.1-SNAPSHOT.jar
    - git commit -m "Update .jar file"
    - git push
  only:
    - Release

deploy-backend:
  stage: deploy
  script:
    - echo "Deploying Success"
    - apt update
    - apt -y install curl
    - curl -s https://api.render.com/deploy/srv-ci6gjtdiuieb62u17e5g?key=-fU8hgE5Ymw
  tags:
    - dalfcs_docker_autoscale
  only:
    - Release

deploy-frontend:
  stage: deploy
  script:
    - echo "Deploying Success"
    - apt update
    - apt -y install curl
    - curl -X POST -d {} https://api.netlify.com/build_hooks/648d24e694a8663c58b939b0
  tags:
    - dalfcs_docker_autoscale
  only:
    - Release
